# Development Docker Compose Override
# This file extends compose.yml for development-specific configurations

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_JPA_SHOW_SQL: true
      LOGGING_LEVEL_ROOT: DEBUG
      SPRING_DEVTOOLS_RESTART_ENABLED: true
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: true
    ports:
      - "8083:8080"
      - "5005:5005" # Debug port
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - target/
            - .mvn/
        - action: rebuild
          path: ./backend/pom.xml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:8083
    ports:
      - "3001:3000" # Different port for dev
    develop:
      watch:
        - action: sync
          path: ./frontend/app
          target: /app/app
        - action: sync
          path: ./frontend/components
          target: /app/components
        - action: sync
          path: ./frontend/lib
          target: /app/lib
        - action: sync
          path: ./frontend/hooks
          target: /app/hooks
        - action: sync
          path: ./frontend/provider
          target: /app/provider
        - action: sync
          path: ./frontend/schema
          target: /app/schema
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: sync+restart
          path: ./frontend/next.config.ts
          target: /app/next.config.ts
        - action: sync+restart
          path: ./frontend/tailwind.config.ts
          target: /app/tailwind.config.ts
        - action: rebuild
          path: ./frontend/package.json

  postgres:
    environment:
      POSTGRES_DB: astroneko_dev
    ports:
      - "5434:5432" # Different port for dev database
